Migration to Pydantic V2
aleph-im/aleph-message pull request #115
Opened 2024-10-31 19:37 UTC by nesitor

2025-04-07 18:02 UTC, aliel approved these changes

2025-04-07 19:03 UTC, olethanh requested changes

2025-04-07 19:03 UTC, olethanh commented on aleph_message/models/__init__.py
> +logging.basicConfig(level=logging.DEBUG)
Do not call basicConfig in libs, it will break  the logging for apps and code that use logging

2025-04-08 07:27 UTC, olethanh approved these changes

2025-04-08 12:46 UTC, merged