CI: Tests were not run on push
aleph-im/aleph-message pull request #24
Opened 2022-09-20 14:32 UTC by hoh

Solution: Add a GitHub workflow to run tests automatically

2022-09-20 15:10 UTC, odesenfans requested changes

2022-09-20 15:10 UTC, odesenfans commented on .github/workflows/tests.yml
> +on: push
I'm still pretty convinced that filtering pushes to main + PRs is enough, but whatever you prefer.

2022-09-20 15:10 UTC, odesenfans commented on .github/workflows/tests.yml
> +        run: docker tag aleph-message:${GITHUB_REF##*/} docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-message-build-cache && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-message-build-
Do you really need a Docker image for this? This seems weird, and will also be incompatible with features like test matrices and so on (i.e. testing with several versions of Python using Github actions). I'd just use a regular cache and run the tests on the CI runner directly.

2022-09-20 15:59 UTC, hoh commented on .github/workflows/tests.yml
> +        run: docker tag aleph-message:${GITHUB_REF##*/} docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-message-build-cache && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-message-build-
I use that Docker image locally and it allows me to run tests independently of my host system, which is useful from a developer point of view.
It would be useful to have CI on that Docker image to prevent it from breaking.

Faster tests without the whole Docker setup and with test matrices would be nice to have, but that would be more work while the Dockerfile is already present.

2022-09-21 10:35 UTC, odesenfans commented on .github/workflows/tests.yml
> +        run: docker tag aleph-message:${GITHUB_REF##*/} docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-message-build-cache && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-message-build-
Okay then.

2022-09-21 10:35 UTC, odesenfans approved these changes

2022-12-15 15:32 UTC, merged