Fix: Any invalid message in a response crashed the entire response
aleph-im/aleph-message pull request #27
Opened 2022-09-22 14:18 UTC by hoh

The code serving the API may return messages that are not valid according the latest version of the schemas. Ignore them with a warning instead of failing the parsing of the entire response.

Closes https://github.com/aleph-im/aleph-client/issues/108

2022-09-22 14:49 UTC, odesenfans requested changes

2022-09-22 14:49 UTC, odesenfans commented on aleph_message/models/__init__.py
> +    def handle_invalid_messages(cls, v: List[Dict]):
You shouldn't assume that v is a list of dicts coming into this function. It should be `Any` with an `isinstance` check.

2022-09-22 14:49 UTC, odesenfans commented on aleph_message/models/__init__.py
> +                message = Message(**message_raw)
Why not `Message.parse_obj(message_raw)`? iirc that would avoid the KeyError.

2022-09-22 14:49 UTC, odesenfans commented on aleph_message/models/__init__.py
> +    def handle_invalid_messages(cls, v: List[Dict]):
Also, not 100% sure on this: are we sure that the validator is not run a second time on the return value of this validator? I wouldn't be surprised it it's the case.

2022-09-22 14:49 UTC, odesenfans commented on aleph_message/tests/test_models.py
> +    with open(path) as fd:
Mixing Path and os.path is weird. Also, pretty sure the join would not work because you never specify to take the parent directory of `__file__`?

```suggestion
    path = Path(__file__).parent.parent / "messages" / "contains_invalid_messages.json"
    with path.open()  as fd:
```

2022-09-23 15:34 UTC, hoh commented
I am wondering if this would not make more sense in `aleph-client`, see the linked Pull Request above.

2022-09-23 17:38 UTC, hoh commented
Replaced by a fix in Aleph-client.

2022-09-23 17:38 UTC, closed without merging